# Execute this instruction to build and deploy this new image
# gcloud builds submit --config cloudbuild.yaml
steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/portfolio:$SHORT_SHA"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: Push image
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/portfolio:$SHORT_SHA"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Deploy
    args:
      - "run"
      - "deploy"
      - "$SERVICE_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/portfolio:$SHORT_SHA"
      - "--region"
      - "$REGION"
    env:
      - "SERVICE_NAME=potfolio"
      - "REGION=us-central1"
